name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Grant execute permission to configure
      run: chmod +x ./configure  # 실행 권한 부여
    - name: configure
      run: ./configure

    - name: make
      run: |
        cd isExpression
        make
