name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Grant execute permission to configure
      run: chmod +x ./configure  # 실행 권한 부여
    - name: configure
      run: ./configure
    - name : cd isExpression
      run : cd isExpression
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
